joshsoftware/intranet-mobile

src/app/components/timesheet/employeeCard.tsx
src/app/components/timesheet/listHeader.tsx
src/app/components/timesheet/listHeaderItem.tsx
src/app/components/timesheet/screens/ManagerScreen.tsx
src/app/components/timesheet/screens/UserScreen.tsx
src/app/components/timesheet/sectionListTimesheet.tsx
src/app/components/timesheet/userTimesheet.tsx

Manager Role view and User Role View Added

Added Manager and timesheet list screens

---

src/app/components/customAccordian/index.tsx
src/app/components/profile/assets/assetView.tsx
src/app/components/profile/cardDetails/cardDetailsElement.tsx
src/app/components/profile/cardDetails/updateSkillsForm.tsx
src/app/screens/userProfile/EmployeeDetails.tsx
src/app/screens/userProfile/PersonalDetails.tsx
src/app/screens/userProfile/Skills.tsx
src/app/types.ts

description view with null data was handled

---

src/app/components/profile/cardDetails/index.tsx
src/app/screens/userProfile/Assets.tsx
src/app/screens/userProfile/Deployment.tsx
src/app/screens/userProfile/EmployeeDetails.tsx
src/app/screens/userProfile/PersonalDetails.tsx
src/app/screens/userProfile/PublicProfile.tsx
src/app/screens/userProfile/Skills.tsx
src/app/screens/userProfile/components/ScreenWrapper.tsx
src/app/screens/userProfile/customTabView/index.tsx
src/app/screens/userProfile/index.tsx

Scrollbar on screen edge
Cards have elevation
Tab bar height increase

User Profile Style Changes

---

package-lock.json
package.json
src/App.tsx
src/app/components/modal/index.tsx
src/app/components/profile/cardDetails/updateSkillsForm.tsx
src/app/components/toast/index.tsx
src/app/screens/TimesheetScreen/timesheet.hooks.ts
src/app/services/timesheet/types.ts
src/app/utils/toast/index.ts

https://trello.com/c/xhIBVFhZ/29-add-toast-in-app
---
Added toast messages with specific colors scheme.
---
---
N/A

toast box added

---

src/app/components/DrawerContent.tsx
src/app/components/TabBar.tsx
src/app/components/header/index.tsx
src/app/navigation/DrawerNavigation.tsx
src/app/navigation/MainNavigator.tsx
src/app/navigation/RootNavigator.tsx
src/app/navigation/types.ts
src/app/screens/ProfileScreen/tabs/Skills.tsx

Unique key prop error in other skills (profile screen)

Menu button opens drawer

---

src/app/components/pickers/pickerSelect.tsx
src/app/screens/TimesheetScreen/component/timesheetForm.tsx
src/app/screens/TimesheetScreen/view/createTimesheet.tsx

Picker select ignores undefined value so null should be passed to ensure that picker select detects a change in value.
Form re validation is set to on submit.

Bug: 39 Form Values does on reset after form submission

---

src/app/screens/ProfileScreen/tabs/EmployeeDetails.tsx
src/app/screens/TimesheetScreen/component/editTimesheetModal.tsx
src/app/screens/TimesheetScreen/view/createTimesheet.tsx

Ticket:
https://trello.com/c/4qg2IOiZ/51-toast-message-appears-when-modal-close-with-cancel-button

toast message reappers when modal close bug fixed

---

src/app/components/DrawerContent.tsx
src/app/navigation/DrawerNavigation.tsx

https://trello.com/c/QBx0lHfN
---
- Resolving 2 bugs in drawer.
1. Disable opening drawer with swipe gesture.
2. Close drawer after navigation.
---
- Add an x in between the brackets to check off a relevant item, eg: [x]
---
- N/A
---
- None

Drawer close and swipe disable

---

src/app/screens/LeaveScreen/leave.hooks.ts

https://trello.com/c/C6CyzaT1
---
- Show email of users without name in leaves filter modal.
---
---
- N/A
---

Show email of users without name in leaves filter modal

---

src/app/screens/ProfileScreen/interface/personalDetails.ts
src/app/screens/ProfileScreen/tabs/PersonalDetails.tsx

https://trello.com/c/fhcvf0eL/63-add-probation-date-in-employee-profile
---
Probation End Date field added in user profile
---

 probation end date

---

src/app/screens/HomeScreen/Calendar/index.tsx
src/app/screens/TimesheetScreen/timesheet.hooks.ts
src/app/utils/date.ts

- <a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IP4i7o2j&#x2F;69-update-calendar-when-user-add-update-delete-timesheets">Update calendar when user add&#x2F;update&#x2F;delete timesheets</a>
---
- Refetch calendar data when timesheets change
---
---
- N/A.
---
- N/A.

Refetch calendar data when timesheets change

---

src/app/navigation/types.ts
src/app/screens/HomeScreen/Calendar/index.tsx
src/app/screens/LeaveScreen/leave.hooks.ts
src/app/screens/TimesheetScreen/component/timesheetForm.tsx
src/app/screens/TimesheetScreen/index.tsx
src/app/screens/TimesheetScreen/view/createTimesheet.tsx
src/app/screens/TimesheetScreen/view/timesheetList/createTimesheetButton.tsx
src/app/screens/TimesheetScreen/view/timesheetList/index.tsx
src/app/utils/home/index.ts

https://trello.com/c/f6UPHGaQ/70-perform-actions-on-calender-date-tap
---
This PR adds the functionality to navigate the timesheet tab to perform a particular action on the calendar date tap.
---

actions perform on date tap in calender

---

src/app/constant/apiRoutes.ts
src/app/screens/HomeScreen/TeamMembersBirthdays/BirthdayCard.tsx
src/app/screens/HomeScreen/TeamMembersBirthdays/index.tsx
src/app/screens/HomeScreen/dashboard.hooks.ts
src/app/screens/HomeScreen/index.tsx
src/app/screens/HomeScreen/teamMembersLeaves/index.tsx
src/app/services/home/index.ts
src/app/services/home/types.ts

- <a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tt8thL8c&#x2F;71-birthdays-on-home-screen">Birthdays on home screen</a>
---
- Added birthday section to home screen
---
---
- N/A.
---
- <img src="https://github.com/joshsoftware/intranet-mobile/assets/124863404/19c3c3c5-4216-471f-8383-ebdbaebcfad4" width="300">

Add birthdays on homescreen

---

src/app/screens/HomeScreen/dashboard.hooks.ts
src/app/services/home/types.ts
src/app/utils/home/index.ts

- <a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OTedxjsl&#x2F;72-wfh-present-in-up-coming-leaves-for-20-days">WFH present in up-coming leaves for 20 days</a>
---
- Hide Work from home leaves on from team leaves on home screen.
---
---
- N/A.
---

Hide WFH Leaves from homescreen team leaves

---

src/app/components/header/index.tsx

- <a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;danCYlng&#x2F;75-profile-header-on-profile-screen">Profile Header on profile screen</a>
---
- Modified Header text in stack screens.
---
---
- N/A.
---

Bold font for back text header in stack screens

---

src/app/utils/home/index.ts

- <a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0gA8uC8x&#x2F;76-handle-holidaytimesheet-filled-case-on-calendar">Handle Holiday+Timesheet filled case on calendar</a>
---
- Handle multiple date types on singe day.
---
---
- N/A.
---
- N/A.

Handle multiple date types on single day

---

.env.sample
.gitignore
README.md
docs/environments_setup.md
docs/firebase_setup.md
docs/release.md

https://trello.com/c/y3SNnqwA/80-create-documentation-for-app
---

Added README, docs

---

src/app/screens/TimesheetScreen/timesheet.hooks.ts
src/app/screens/TimesheetScreen/view/timesheetList/index.tsx

- 
---
- Calendar now updates when timesheet is deleted.
---
---
- N/A
---

Calendar updates when manager deletes timesheet

---

src/app/components/DrawerContent.tsx
src/app/constant/apiRoutes.ts

https://trello.com/c/ihrUEMuf/86-add-privacy-policy-label-in-app
---
Privacy policy label added
---
---

privacy policy route added

---

src/app/components/pickers/NativeDatePicker.tsx
src/app/components/pickers/datePicker.tsx
src/app/components/pickers/dateRange.tsx
src/app/screens/HomeScreen/Calendar/index.tsx
src/app/screens/LeaveScreen/TabScreen.tsx
src/app/screens/LeaveScreen/component/FilterModal.tsx
src/app/screens/TimesheetScreen/component/timesheetForm.tsx
src/app/screens/TimesheetScreen/view/employeeList.tsx
src/app/screens/TimesheetScreen/view/timesheetList/index.tsx
src/app/utils/date.ts

Changes:
- bug fix constant dates are now functions to enforce use of real current date when required
- toggle picker before updating date to prevent reopening of date picker
- removed unused value prop from DatePicker of date range component

BugFix: constant dates are now functions to retreive real current date

---

src/app/Peerly/screens/HomeScreen/index.tsx

Change the tab names as per shailendra given
